name: Inputs
on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                  - debug
                  - warning
                  - error
            print_tags:
                description: 'Print tags'
                required: true
                type: boolean
            tags:
                description: 'Test Scenario Tags'
                required: true
                type: string
            environment:
                description: 'Environment'
                required: true
                type: environment

jobs:
    print-tag:
        runs-on: ubuntu-latest
        steps:
        - name: Print the input tag to STDOUT
          run: echo The tags are ${{ inputs.tags }}
        - name: print the environment
          run: echo The tags are  ${{ inputs.environment }}          