name: Concurrency
on: [push]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    concurrency_job:
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: sleep 20
        